baseURL = 'https://helmuth-projects.com/'
languageCode = 'en-US'
defaultContentLanguage = 'en-us'
title = 'Helmuth Projects - Explore the World of Needle Arts' # Title on Meta Tags
paginate = 20
theme = 'beta'
enableRobotsTXT = true
disableKinds = ['section', 'posts']
disableHugoGeneratorInject = true

[permalinks]
  posts = '/:title/'
  pages = '/:title/'


[taxonomies]
  category = 'categories'

[outputs]
  page = ['HTML']
  home = ['HTML','RSS']
  section = ['HTML']
  taxonomyTerm = ['HTML']
  taxonomy = ['HTML']

[outputFormats]
  [outputFormats.RSS]
    mediatype = 'application/rss'
    baseName = 'rss'    

[params]
  title = 'Helmuth Projects' # Title on Header
  # tagline = ''
  description = 'Discover the beauty and artistry of embroidery and crafts. From cross-stitch to knitting, quilting to crochet, find inspiration and learn new techniques to bring your handmade creations to life'
  author = 'Embroidery Expert'
  recentposts = 10

[menu]

  [[menu.main]]
    identifier = 'categories'
    name = 'Categories'
    url = '/categories/'
    weight = 1

  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2

  [[menu.main]]
    identifier = 'privacy-policy'
    name = 'Privacy Policy'
    url = '/privacy-policy/'
    weight = 3

  [[menu.main]]
    identifier = 'dmca'
    name = 'DMCA'
    url = '/dmca/'
    weight = 4

# [menu]

#   [[menu.socialsidebar]]
#     identifier = 'facebook'
#     name = 'facebook'
#     url = '#'
#     icon = '<i class='fa fa-facebook'></i>'
#     weight = '1'